language: php

notifications:
    email:
        recipients:
            - dev@dmk-ebusiness.de
        on_success: change
        on_failure: always

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

env:
    - TYPO3_VERSION="^8.7.0"
    - TYPO3_VERSION="^9.5.0"

path:
    - TEST_PATH = "tests"

matrix:
    exclude:
        - php: 7.0
          env: TYPO3_VERSION="^8.7.0"
          path: TEST_PATH = "tests"
        - php: 7.0
          env: TYPO3_VERSION="^9.5.0"
          path: TEST_PATH = "tests"
        - php: 7.1
          env: TYPO3_VERSION="^9.5.0"
          path: TEST_PATH = "tests"
        - php: 7.2
          env: TYPO3_VERSION="^9.5.0"
          path: TEST_PATH = "tests"
        - php: 7.3
        env: TYPO3_VERSION="^9.5.0"
        path: TEST_PATH = "tests"

sudo: false

addons:
    apt:
        packages:
            - parallel

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer --version

before_script:
    - |
        if [ $TYPO3_VERSION == "^9.5.0" ]; then
          composer require typo3/minimal="$TYPO3_VERSION"
        else
          travis_wait 30 composer require typo3/cms="$TYPO3_VERSION"
        fi
    - composer require -o digedag/rn-base="dev-master"
    # Restore composer.json
    - git checkout composer.json
    - export TYPO3_PATH_WEB=$PWD/.Build/Web
    - cp $PWD/.Build/Web/typo3conf/ext/mklog/Tests/Fixtures/LocalConfiguration.php $PWD/.Build/Web/typo3conf/LocalConfiguration.php

script:
    - >
        echo;
        echo "Running unit tests";
        .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml $TEST_PATH
# disabled, because there are direct tx_rnbase::load calls in the files!
#  - >
#    echo;
#    echo "Running php lint";
#    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;